---
- name: stop and remove
  docker:
      name: db
      image: db
      state: absent
- name: start container db
  docker:
      name: db
      registry: 10.240.0.2:5000
      insecure_registry: yes
      image: 10.240.0.2:5000/db:v2
      detach: True
      state: started
      volumes: /var/lib/mysql:/var/lib/mysql
      ports:
      - 3306:3306
      restart_policy: always
      privileged: yes
      env: MYSQL_ROOT_PASSWORD=123456
