---
- hosts: dev-servers
  vars:
	user1: test
	user2: test2

  tasks:
  - name: create user 
    user: name=${user1} shell=/bin/bash

  - name: create user 
    user: name=${user2} shell=/bin/bash 

  - name: create ssh directory 
    file: path=/home/${user1}/.ssh state=directory

  - name: create ssh directory 
    file: path=/home/${user2}/.ssh state=directory

  - name: copy ssh key 
    copy: src=/soft/${user1}/authorized_keys dest=/home/${user1}/.ssh/

  - name: copy ssh key 
    copy: src=/soft/${user2}/authorized_keys dest=/home/${user2}/.ssh/

  - name: change ownership 
    file: path=/home/${user1}/ owner=${user1} group=${user1} state=directory recurse=yes

  - name: change ownership 
    file: path=/home/${user2}/ owner=${user2} group=${user2} state=directory recurse=yes

