---
- hosts: dev-servers
  vars:
	user1: test1
	user2: test2
  tasks:
  - name: group admin sudo no password (search and replace)
    lineinfile: dest=/etc/sudoers regexp='^%admin' line='%admin ALL=(ALL) NOPASSWD:ALL'
  - name: delete line if exits
    lineinfile: dest=/etc/sudoers regexp='^${user1}' state=absent
  - name: craete group admin
    group: name=admin state=present
  - name: add group admin
    user: name=${user1} groups=admin append=yes
  - name: add user to group admin
    user: name=${user2} groups=admin append=yes

