---
- hosts: all
  tasks:
        - name: install epel repo
          yum:
                name: "http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
                state: present
        - name: install docker
          yum: pkg=docker-io state=present
        - name: install git
          yum: pkg=git state=present
	- service: name=sshd state=restarted
