---
- name: stop and remove proxy
  docker:
      name: proxy
      image: proxy
      state: absent
- name: start container proxy
  docker:
      name: proxy
      image: proxy
      detach: True
      state: started
      volumes: /data/www:/data/www
      extra_hosts:
	test01: 1.2.3.4
      ports:
      - 80:80
      - 443:443
      restart_policy: always
      privileged: yes
- name: stop and remove apps
  docker:
      name: apps
      image: apps
      state: absent
- name: start container apps
  docker:
      name: apps
      image: apps
      detach: True
      state: started
      volumes: /data/www:/data/www
      extra_hosts:
	test01: 1.2.3.4
      ports:
      - 21:21
      - 9000:9000
      restart_policy: always
      privileged: yes
